<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicinesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::unprepared('INSERT INTO `medicines` (`id`, `name`, `salt`, `category`, `uses`, `typical_dosage`, `disease_id`, `introduction`, `benefits`, `side_effects`, `substitutes`) VALUES
(1, \'Aspirin\', \'Acetylsalicylic Acid\', \'Antiplatelet\', \'Prevents clot formation\', \'75 mg\', 1, \'Aspirin is a commonly used medicine to treat conditions such as prevents clot formation.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Acetylsalicylic Acid generics\'),
(2, \'Atorvastatin\', \'Atorvastatin Calcium\', \'Statin\', \'Lowers cholesterol\', \'40 mg\', 1, \'Atorvastatin is a commonly used medicine to treat conditions such as lowers cholesterol.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Atorvastatin Calcium generics\'),
(3, \'Salbutamol\', \'Albuterol Sulfate\', \'Bronchodilator\', \'Quick-relief inhaler\', \'100 mcg\', 10, \'Salbutamol is a commonly used medicine to treat conditions such as quick-relief inhaler.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Albuterol Sulfate generics\'),
(4, \'Tiotropium\', \'Tiotropium Bromide\', \'Anticholinergic\', \'Long-acting bronchodilator\', \'18 mcg\', 2, \'Tiotropium is a commonly used medicine to treat conditions such as long-acting bronchodilator.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Tiotropium Bromide generics\'),
(5, \'Paracetamol\', \'Acetaminophen\', \'Analgesic\', \'Pain relief\', \'500 mg\', NULL, \'Paracetamol is a commonly used medicine to treat conditions such as pain relief.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Acetaminophen generics\'),
(6, \'Omeprazole\', \'Omeprazole\', \'Proton Pump Inhibitor\', \'Reduces acid production\', \'20 mg\', NULL, \'Omeprazole is a commonly used medicine to treat conditions such as reduces acid production.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Omeprazole generics\'),
(7, \'Nitroglycerin\', \'Glyceryl Trinitrate\', \'Vasodilator\', \'Relieves chest pain\', \'0.4 mg\', 1, \'Nitroglycerin is a commonly used medicine to treat conditions such as relieves chest pain.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Glyceryl Trinitrate generics\'),
(8, \'Metoprolol\', \'Metoprolol Tartrate\', \'Beta Blocker\', \'Lowers heart rate and blood pressure\', \'50 mg\', NULL, \'Metoprolol is a commonly used medicine to treat conditions such as lowers heart rate and blood pressure.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Metoprolol Tartrate generics\'),
(9, \'Amlodipine\', \'\', \'\', \'Calcium channel blocker\', \'5 mg\', 4, \'Amlodipine is a commonly used medicine to treat conditions such as calcium channel blocker.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(10, \'Losartan\', \'Losartan Potassium\', \'ARB\', \'Angiotensin receptor blocker\', \'50 mg\', NULL, \'Losartan is a commonly used medicine to treat conditions such as angiotensin receptor blocker.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Losartan Potassium generics\'),
(11, \'Warfarin\', \'Warfarin Sodium\', \'Anticoagulant\', \'Long-term anticoagulation\', \'5 mg\', NULL, \'Warfarin is a commonly used medicine to treat conditions such as long-term anticoagulation.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Warfarin Sodium generics\'),
(12, \'Amiodarone\', \'\', \'\', \'Restores normal rhythm\', \'200 mg\', NULL, \'Amiodarone is a commonly used medicine to treat conditions such as restores normal rhythm.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(13, \'Furosemide\', \'Furosemide\', \'Diuretic\', \'Reduces fluid overload\', \'40 mg\', NULL, \'Furosemide is a commonly used medicine to treat conditions such as reduces fluid overload.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Furosemide generics\'),
(14, \'Enalapril\', \'Enalapril Maleate\', \'ACE Inhibitor\', \'ACE inhibitor for heart function\', \'10 mg\', NULL, \'Enalapril is a commonly used medicine to treat conditions such as ace inhibitor for heart function.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Enalapril Maleate generics\'),
(15, \'Ibuprofen\', \'Ibuprofen\', \'NSAID\', \'Reduces inflammation\', \'400 mg\', NULL, \'Ibuprofen is a commonly used medicine to treat conditions such as reduces inflammation.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Ibuprofen generics\'),
(16, \'Colchicine\', \'\', \'\', \'Prevents recurrence\', \'0.6 mg\', NULL, \'Colchicine is a commonly used medicine to treat conditions such as prevents recurrence.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(17, \'Propranolol\', \'\', \'\', \'Reduces palpitations\', \'40 mg\', NULL, \'Propranolol is a commonly used medicine to treat conditions such as reduces palpitations.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(18, \'Budesonide\', \'\', \'\', \'Preventive corticosteroid\', \'200 mcg\', 10, \'Budesonide is a commonly used medicine to treat conditions such as preventive corticosteroid.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(19, \'Amoxicillin\', \'Amoxicillin Trihydrate\', \'Antibiotic\', \'Antibiotic for bacterial pneumonia\', \'500 mg\', NULL, \'Amoxicillin is a commonly used medicine to treat conditions such as antibiotic for bacterial pneumonia.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Amoxicillin Trihydrate generics\'),
(20, \'Azithromycin\', \'\', \'\', \'Broad-spectrum antibiotic\', \'500 mg\', NULL, \'Azithromycin is a commonly used medicine to treat conditions such as broad-spectrum antibiotic.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(21, \'Heparin\', \'\', \'\', \'Immediate anticoagulation\', \'5000 units\', NULL, \'Heparin is a commonly used medicine to treat conditions such as immediate anticoagulation.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(22, \'Isoniazid\', \'\', \'\', \'Core anti-TB drug\', \'300 mg\', NULL, \'Isoniazid is a commonly used medicine to treat conditions such as core anti-tb drug.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(23, \'Rifampicin\', \'\', \'\', \'Broad-spectrum anti-TB antibiotic\', \'600 mg\', NULL, \'Rifampicin is a commonly used medicine to treat conditions such as broad-spectrum anti-tb antibiotic.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(24, \'Dextromethorphan\', \'Dextromethorphan Hydrobromide\', \'Cough Suppressant\', \'Suppresses cough\', \'10 ml\', NULL, \'Dextromethorphan is a commonly used medicine to treat conditions such as suppresses cough.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Dextromethorphan Hydrobromide generics\'),
(25, \'Guaifenesin\', \'Guaifenesin\', \'Expectorant\', \'Loosens mucus\', \'200 mg\', NULL, \'Guaifenesin is a commonly used medicine to treat conditions such as loosens mucus.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Guaifenesin generics\'),
(26, \'Pirfenidone\', \'\', \'\', \'Anti-fibrotic agent\', \'801 mg\', NULL, \'Pirfenidone is a commonly used medicine to treat conditions such as anti-fibrotic agent.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(27, \'Prednisone\', \'\', \'\', \'Reduces inflammation\', \'10 mg\', NULL, \'Prednisone is a commonly used medicine to treat conditions such as reduces inflammation.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(28, \'Pancrelipase\', \'\', \'\', \'Enzyme replacement\', \'500 mg\', 3, \'Pancrelipase is a commonly used medicine to treat conditions such as enzyme replacement.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(29, \'Tramadol\', \'\', \'\', \'Pain relief\', \'50 mg\', NULL, \'Tramadol is a commonly used medicine to treat conditions such as pain relief.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(30, \'Gemcitabine\', \'Gemcitabine HCl\', \'Chemotherapy\', \'Chemotherapy\', \'1000 mg/m2\', NULL, \'Gemcitabine is a commonly used medicine to treat conditions such as chemotherapy.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Gemcitabine HCl generics\'),
(31, \'Nab-paclitaxel\', \'\', \'\', \'Combination chemo\', \'125 mg/m2\', NULL, \'Nab-paclitaxel is a commonly used medicine to treat conditions such as combination chemo.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(32, \'Ranitidine\', \'Ranitidine Hydrochloride\', \'H2 Blocker\', \'Reduces stomach acid\', \'150 mg\', NULL, \'Ranitidine is a commonly used medicine to treat conditions such as reduces stomach acid.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Ranitidine Hydrochloride generics\'),
(33, \'Ursodeoxycholic Acid\', \'\', \'\', \'Dissolves small stones\', \'300 mg\', NULL, \'Ursodeoxycholic Acid is a commonly used medicine to treat conditions such as dissolves small stones.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Other drugs in same category\'),
(34, \'Clarithromycin\', \'Clarithromycin\', \'Antibiotic\', \'Eradicates H. pylori\', \'500 mg\', NULL, \'Clarithromycin is a commonly used medicine to treat conditions such as eradicates h. pylori.\', \'- Provides fast relief from symptoms\r\n- Helps manage or prevent disease progression\r\n- Often prescribed as part of standard treatment\r\n- Cost-effective and widely available\', \'- Common: Nausea, dizziness, headache\r\n- Occasional: Stomach upset, rash\r\n- Rare: Severe allergic reactions or bleeding\', \'Clarithromycin generics\');');
    }
}
