<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SymptomsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::unprepared('INSERT INTO `symptoms` (`id`, `name`) VALUES
(9, \'abdominal pain\'),
(93, \'acne\'),
(145, \'agitation\'),
(94, \'anxiety\'),
(136, \'bleeding\'),
(132, \'bleeding gums\'),
(37, \'bloating\'),
(95, \'blood in stool\'),
(14, \'blurred vision\'),
(96, \'breast lump\'),
(97, \'breast pain\'),
(77, \'burning urination\'),
(21, \'chest discomfort\'),
(1, \'chest pain\'),
(8, \'chest tightness\'),
(79, \'chills\'),
(6, \'chronic cough\'),
(71, \'cold intolerance\'),
(66, \'confusion\'),
(134, \'conjunctivitis\'),
(137, \'constipation\'),
(23, \'cough\'),
(22, \'coughing\'),
(25, \'coughing up blood\'),
(98, \'daytime sleepiness\'),
(81, \'decreased urine output\'),
(99, \'delusions\'),
(83, \'depressed mood\'),
(100, \'diarrhea\'),
(34, \'difficulty swallowing\'),
(17, \'dizziness\'),
(29, \'dry cough\'),
(101, \'ear discharge\'),
(90, \'ear pain\'),
(102, \'excessive hair growth\'),
(68, \'excessive thirst\'),
(103, \'eye pain\'),
(104, \'facial pain\'),
(5, \'fatigue\'),
(11, \'fever\'),
(105, \'frequent infections\'),
(69, \'frequent urination\'),
(106, \'hallucinations\'),
(13, \'headache\'),
(92, \'hearing loss\'),
(140, \'heart murmur\'),
(32, \'heartburn\'),
(72, \'heat intolerance\'),
(144, \'hydrophobia\'),
(35, \'indigestion\'),
(85, \'insomnia\'),
(107, \'irregular periods\'),
(91, \'irritability\'),
(88, \'itchy eyes\'),
(108, \'itchy skin\'),
(31, \'jaundice\'),
(147, \'jaw pain\'),
(73, \'joint pain\'),
(109, \'joint swelling\'),
(110, \'leg numbness\'),
(111, \'leg pain on walking\'),
(18, \'leg swelling\'),
(142, \'lockjaw\'),
(67, \'loss of consciousness\'),
(84, \'loss of interest\'),
(80, \'loss of taste\'),
(112, \'mania\'),
(113, \'memory loss\'),
(74, \'morning stiffness\'),
(149, \'mouth sores\'),
(78, \'muscle pain\'),
(141, \'muscle stiffness\'),
(114, \'muscle weakness\'),
(89, \'nasal congestion\'),
(4, \'nausea\'),
(115, \'neck stiffness\'),
(27, \'night sweats\'),
(15, \'nosebleeds\'),
(116, \'pain in leg\'),
(117, \'painful periods\'),
(76, \'pale skin\'),
(16, \'palpitations\'),
(146, \'parotid swelling\'),
(118, \'pelvic pain\'),
(19, \'persistent cough\'),
(133, \'petechiae\'),
(28, \'phlegm production\'),
(24, \'rapid heartbeat\'),
(12, \'rapid pulse\'),
(75, \'rash\'),
(119, \'red eyes\'),
(120, \'redness\'),
(33, \'regurgitation\'),
(121, \'rigidity\'),
(87, \'runny nose\'),
(122, \'scaly rash\'),
(65, \'seizures\'),
(64, \'sensitivity to light\'),
(135, \'severe abdominal pain\'),
(20, \'sharp chest pain\'),
(2, \'shortness of breath\'),
(123, \'slow movement\'),
(86, \'sneezing\'),
(124, \'snoring\'),
(138, \'sore throat\'),
(143, \'spasms\'),
(30, \'steatorrhea\'),
(36, \'stomach pain\'),
(139, \'strawberry tongue\'),
(82, \'sudden weakness\'),
(3, \'sweating\'),
(148, \'swollen lymph nodes\'),
(125, \'syncope\'),
(126, \'tingling\'),
(127, \'tremor\'),
(128, \'vertigo\'),
(129, \'vesicular rash\'),
(130, \'vision loss\'),
(10, \'vomiting\'),
(70, \'weight gain\'),
(26, \'weight loss\'),
(7, \'wheezing\'),
(131, \'withdrawal\');');
    }
}
