<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SymptomMapTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::unprepared('INSERT INTO `symptom_map` (`id`, `symptom`, `disease`, `score`) VALUES
(1, \'chest pain\', \'Myocardial Infarction\', 75),
(2, \'shortness of breath\', \'Myocardial Infarction\', 75),
(3, \'sweating\', \'Myocardial Infarction\', 75),
(4, \'nausea\', \'Myocardial Infarction\', 75),
(5, \'fatigue\', \'Myocardial Infarction\', 75),
(6, \'chronic cough\', \'Chronic Obstructive Pulmonary Disease (COPD)\', 75),
(7, \'shortness of breath\', \'Chronic Obstructive Pulmonary Disease (COPD)\', 75),
(8, \'wheezing\', \'Chronic Obstructive Pulmonary Disease (COPD)\', 75),
(9, \'chest tightness\', \'Chronic Obstructive Pulmonary Disease (COPD)\', 75),
(10, \'fatigue\', \'Chronic Obstructive Pulmonary Disease (COPD)\', 75),
(11, \'abdominal pain\', \'Acute Pancreatitis\', 75),
(12, \'nausea\', \'Acute Pancreatitis\', 75),
(13, \'vomiting\', \'Acute Pancreatitis\', 75),
(14, \'fever\', \'Acute Pancreatitis\', 75),
(15, \'rapid pulse\', \'Acute Pancreatitis\', 75),
(16, \'chest pain\', \'Angina Pectoris\', 75),
(17, \'shortness of breath\', \'Angina Pectoris\', 75),
(18, \'fatigue\', \'Angina Pectoris\', 75),
(19, \'headache\', \'Hypertension\', 75),
(20, \'blurred vision\', \'Hypertension\', 75),
(21, \'chest pain\', \'Hypertension\', 75),
(22, \'nosebleeds\', \'Hypertension\', 75),
(23, \'palpitations\', \'Atrial Fibrillation\', 75),
(24, \'shortness of breath\', \'Atrial Fibrillation\', 75),
(25, \'fatigue\', \'Atrial Fibrillation\', 75),
(26, \'dizziness\', \'Atrial Fibrillation\', 75),
(27, \'shortness of breath\', \'Congestive Heart Failure\', 75),
(28, \'leg swelling\', \'Congestive Heart Failure\', 75),
(29, \'fatigue\', \'Congestive Heart Failure\', 75),
(30, \'persistent cough\', \'Congestive Heart Failure\', 75),
(31, \'sharp chest pain\', \'Pericarditis\', 75),
(32, \'fever\', \'Pericarditis\', 75),
(33, \'fatigue\', \'Pericarditis\', 75),
(34, \'shortness of breath\', \'Pericarditis\', 75),
(35, \'palpitations\', \'Mitral Valve Prolapse\', 75),
(36, \'chest discomfort\', \'Mitral Valve Prolapse\', 75),
(37, \'fatigue\', \'Mitral Valve Prolapse\', 75),
(38, \'dizziness\', \'Mitral Valve Prolapse\', 75),
(39, \'wheezing\', \'Asthma\', 75),
(40, \'coughing\', \'Asthma\', 75),
(41, \'shortness of breath\', \'Asthma\', 75),
(42, \'chest tightness\', \'Asthma\', 75),
(43, \'fever\', \'Pneumonia\', 75),
(44, \'cough\', \'Pneumonia\', 75),
(45, \'shortness of breath\', \'Pneumonia\', 75),
(46, \'chest pain\', \'Pneumonia\', 75),
(47, \'chest pain\', \'Pulmonary Embolism\', 75),
(48, \'shortness of breath\', \'Pulmonary Embolism\', 75),
(49, \'rapid heartbeat\', \'Pulmonary Embolism\', 75),
(50, \'coughing up blood\', \'Pulmonary Embolism\', 75),
(51, \'persistent cough\', \'Tuberculosis\', 75),
(52, \'weight loss\', \'Tuberculosis\', 75),
(53, \'fever\', \'Tuberculosis\', 75),
(54, \'night sweats\', \'Tuberculosis\', 75),
(55, \'cough\', \'Bronchitis\', 75),
(56, \'phlegm production\', \'Bronchitis\', 75),
(57, \'chest discomfort\', \'Bronchitis\', 75),
(58, \'fatigue\', \'Bronchitis\', 75),
(59, \'dry cough\', \'Interstitial Lung Disease\', 75),
(60, \'shortness of breath\', \'Interstitial Lung Disease\', 75),
(61, \'fatigue\', \'Interstitial Lung Disease\', 75),
(62, \'weight loss\', \'Interstitial Lung Disease\', 75),
(63, \'abdominal pain\', \'Chronic Pancreatitis\', 75),
(64, \'steatorrhea\', \'Chronic Pancreatitis\', 75),
(65, \'weight loss\', \'Chronic Pancreatitis\', 75),
(66, \'nausea\', \'Chronic Pancreatitis\', 75),
(67, \'jaundice\', \'Pancreatic Cancer\', 75),
(68, \'abdominal pain\', \'Pancreatic Cancer\', 75),
(69, \'weight loss\', \'Pancreatic Cancer\', 75),
(70, \'fatigue\', \'Pancreatic Cancer\', 75),
(71, \'heartburn\', \'Gastroesophageal Reflux Disease (GERD)\', 75),
(72, \'regurgitation\', \'Gastroesophageal Reflux Disease (GERD)\', 75),
(73, \'chest pain\', \'Gastroesophageal Reflux Disease (GERD)\', 75),
(74, \'difficulty swallowing\', \'Gastroesophageal Reflux Disease (GERD)\', 75),
(75, \'abdominal pain\', \'Gallstone Disease (Cholelithiasis)\', 75),
(76, \'nausea\', \'Gallstone Disease (Cholelithiasis)\', 75),
(77, \'vomiting\', \'Gallstone Disease (Cholelithiasis)\', 75),
(78, \'indigestion\', \'Gallstone Disease (Cholelithiasis)\', 75),
(79, \'stomach pain\', \'Peptic Ulcer Disease\', 75),
(80, \'bloating\', \'Peptic Ulcer Disease\', 75),
(81, \'nausea\', \'Peptic Ulcer Disease\', 75),
(82, \'vomiting\', \'Peptic Ulcer Disease\', 75);');
    }
}
